import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationDesktop } from "@/components/navigation/desktop/navigation";
import logo from "@/public/icon.svg";
import Image from "next/image";
import { Heart, ShoppingCart } from "lucide-react";
import NavigationMobile from "@/components/navigation/mobile/navigation";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header className="flex justify-between items-center bg-header px-8 py-4 sticky top-0">
          <Link href="/" className="hidden lg:block">
            <Image src={logo} alt="logo" height={50} width={50} />
          </Link>
          <NavigationDesktop />
          <NavigationMobile />
          <div className="flex space-x-2">
            <Heart className="" aria-hidden="true" />
            <ShoppingCart className="" aria-hidden="true" />
          </div>
        </header>
        {children}
        <footer className="mt-auto bg-slate-600">
          <div className="py-5">
            <p>Footer</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
