import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import logo from "@/public/icon.svg";
import Image from "next/image";
import { Heart, Search, ShoppingCart } from "lucide-react";
import Link from "next/link";
import NavMenu from "@/components/navigation/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Родна Продукция",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header className="flex justify-between items-center px-8 py-4 sticky top-0 z-10 bg-white border-b">
          <Link href="/" className="hidden lg:block">
            <Image src={logo} alt="logo" className="border rounded-full p-2 max-w-20" />
          </Link>
          <NavMenu />
          <div className="flex space-x-2">
            <Search />
            <Heart className="" aria-hidden="true" />
            <ShoppingCart className="" aria-hidden="true" />
          </div>
        </header>
        {children}
        <footer className="mt-auto bg-slate-600">
          <div className="py-5">
            <p>Footer</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
